In [4]:
'''
N 维数组对象 ndarray，它是一系列同类型数据的集合，以 0 下标为开始进行集合中元素的索引。
ndarray 对象是用于存放同类型元素的多维数组。ndarray 中的每个元素在内存中都有相同存储大小的区域。

ndarray 内部由以下内容组成：
指向数据（内存或内存映射文件中的一块数据）的指针。数据类型或 dtype，描述在数组中的固定大小值的格子。
表示数组形状（shape）的元组，表示各维度大小的元组。跨度元组（stride），整数指的是为了前进到当前维度下一个元素需要"跨过"的字节数。
'''
import numpy as np

In [5]:
#属性
'''
.size属性：数组元素个数
.shape属性：数组的形状
.dtype属性：数组元素的数据类型
.ndim属性：数组的维度
.itemsize属性：数组单个元素占用内存空间的字节数
.nbytes属性：数组所有元素占用内存空间的字节数
.flat属性：数组（一维化之后）元素的迭代器
.base属性：数组的基对象（如果数组共享了其他数组的内存空间）
'''

'\n.size属性：数组元素个数\n.shape属性：数组的形状\n.dtype属性：数组元素的数据类型\n.ndim属性：数组的维度\n.itemsize属性：数组单个元素占用内存空间的字节数\n.nbytes属性：数组所有元素占用内存空间的字节数\n.flat属性：数组（一维化之后）元素的迭代器\n.base属性：数组的基对象（如果数组共享了其他数组的内存空间）\n'

In [7]:
#创建ndarray对象

#一维数组
#方法一：使用array函数，通过list创建数组对象
array1 = np.array([1, 2, 3, 4, 5])
print(array1)
#方法二：使用arange函数，指定取值范围创建数组对象
array2 = np.arange(0, 20, 2)
print(array2)
#方法三：使用linspace函数，用指定范围均匀间隔的数字创建数组对象
array3 = np.linspace(-5, 5, 101)
print(array3)
#方法四：使用numpy.random模块的函数生成随机数创建数组对象
array4 = np.random.rand(10)
print(array4)

#二维数组，多维同理
#方法一：使用array函数，通过嵌套的list创建数组对象
array7 = np.array([[1, 2, 3], [4, 5, 6]])
print(array7)
#方法二：使用zeros、ones、full函数指定数组的形状创建数组对象
array8 = np.zeros((3, 4))
print(array8)
array9 = np.ones((3, 4))
print(array9)
array10 = np.full((3, 4), 10)
print(array10)
#方法三：使用eye函数创建单位矩阵
array11 = np.eye(4)
print(array11)
#方法四：通过reshape将一维数组变成二维数组
array12 = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
print(array12)
#提示：reshape是ndarray对象的一个方法，使用reshape方法时需要确保调形后的数组元素个数与调形前数组元素个数保持一致，否则将会产生异常。
#方法五：通过numpy.random模块的函数生成随机数创建数组对象
array13 = np.random.rand(3, 4)
print(array13)



[1 2 3 4 5]
[ 0  2  4  6  8 10 12 14 16 18]
[-5.  -4.9 -4.8 -4.7 -4.6 -4.5 -4.4 -4.3 -4.2 -4.1 -4.  -3.9 -3.8 -3.7
 -3.6 -3.5 -3.4 -3.3 -3.2 -3.1 -3.  -2.9 -2.8 -2.7 -2.6 -2.5 -2.4 -2.3
 -2.2 -2.1 -2.  -1.9 -1.8 -1.7 -1.6 -1.5 -1.4 -1.3 -1.2 -1.1 -1.  -0.9
 -0.8 -0.7 -0.6 -0.5 -0.4 -0.3 -0.2 -0.1  0.   0.1  0.2  0.3  0.4  0.5
  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9
  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7  2.8  2.9  3.   3.1  3.2  3.3
  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1  4.2  4.3  4.4  4.5  4.6  4.7
  4.8  4.9  5. ]
[0.7179818  0.82049138 0.78466104 0.25035791 0.39361647 0.75371054
 0.02817537 0.2965138  0.39956142 0.30473847]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 2 3]
 [4 5 6]]
[[0.6438521  0.80796669 0.3903566  0.2201266 ]
 [0.39282362 0.21828214 0.72432513 0.42430169

In [14]:
#索引切片
'''
普通索引 array1[0] array7[0][1]
切片是形如[开始索引:结束索引:步长]的语法，通过指定开始索引（默认值无穷小）、结束索引（默认值无穷大）和步长（默认值1），
从数组中取出指定部分的元素并构成新的数组。因为开始索引、结束索引和步长都有默认值，所以它们都可以省略，
如果不指定步长，第二个冒号也可以省略。一维数组的切片运算跟Python中的list类型的切片非常类似.
'''
arrayX = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arrayX)
print(arrayX[2])  
print(arrayX[2, :])
print(arrayX[2:, :])  
print(arrayX[1:2, :2])
print(arrayX[::2, ::2])
print(arrayX[::-2, ::-2])

#花式索引（Fancy indexing）是指利用整数数组进行索引，这里所说的整数数组可以是NumPy的ndarray，
#也可以是Python中list、tuple等可迭代类型，可以使用正向或负向索引。
array25 = np.array([50, 30, 15, 20, 40])
array25[[0, 1, -1]]
array26 = np.array([[30, 20, 10], [40, 60, 50], [10, 90, 80]])
# 取二维数组的第1行和第3行
array26[[0, 2]]

#布尔索引就是通过布尔类型的数组对数组元素进行索引，布尔类型的数组可以手动构造，也可以通过关系运算来产生布尔类型的数组。
array27 = np.arange(1, 10)
array27 >= 5
~(array27 >= 5)
array27[array27 >= 5]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[7 8 9]
[7 8 9]
[[ 7  8  9]
 [10 11 12]]
[[4 5]]
[[1 3]
 [7 9]]
[[12 10]
 [ 6  4]]


In [ ]:
#ndarray对象的统计方法主要包括：sum()、mean()、std()、var()、min()、max()、argmin()、argmax()、cumsum()等，
#分别用于对数组中的元素求和、求平均、求标准差、求方差、找最大、找最小、求累积和等
array28 = np.array([1, 2, 3, 4, 5, 5, 4, 3, 2, 1])
print(array28.sum())
print(array28.mean())
print(array28.max())
print(array28.min())
print(array28.std())
print(array28.var())
print(array28.cumsum())


In [16]:
#all() / any()方法：判断数组是否所有元素都是True / 判断数组是否有为True的元素。
#astype()方法：拷贝数组，并将数组中的元素转换为指定的类型。
#dot()方法：实现一个数组和另一个数组的点积运算。
array29 = np.array([3, 4])
array30 = np.array([5, 6])
print(array29.dot(array30))
array31 = np.array([[1, 2, 3], [4, 5, 6]])
array32 = np.array([[1, 2], [3, 4], [5, 6]])
print(array31.dot(array32))

#dump()方法：保存数组到文件中，可以通过NumPy中的load()函数从保存的文件中加载数据创建数组。
    #array31.dump('array31-data')
    #array32 = np.load('array31-data', allow_pickle=True)
    #print(array32)
#fill()方法：向数组中填充指定的元素。
#flatten()方法：将多维数组扁平化为一维数组。
print(array32.flatten())
#nonzero()方法：返回非0元素的索引。
#round()方法：对数组中的元素做四舍五入操作。
#sort()方法：对数组进行就地排序。
array33 = np.array([35, 96, 12, 78, 66, 54, 40, 82])
array33.sort()
print(array33)
#swapaxes()和transpose()方法：交换数组指定的轴。
# 指定需要交换的两个轴，顺序无所谓
print(array32.swapaxes(0, 1))
# 对于二维数组，transpose相当于实现了矩阵的转置
print(array32.transpose())
#take()方法：从数组中取指定索引的元素，类似于花式索引。
array34 = array33.take([0, 2, -3, -1])
print(array34)
#tolist()方法：将数组转成Python中的list。

39
[[22 28]
 [49 64]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[12 35 40 54 66 78 82 96]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[12 40 78 96]


In [ ]:
#当需要对数组元素进行运算时，不用编写循环代码遍历每个元素，所有的运算都会自动的矢量化（使用高效底层语言代码对数据序列进行数学操作）。
#简单的说就是，NumPy中的数学运算和数学函数会自动作用于数组中的每个成员。

In [ ]:
#通用二元函数
'''
add(x, y) / substract(x, y)	加法函数 / 减法函数
multiply(x, y) / divide(x, y)	乘法函数 / 除法函数
floor_divide(x, y) / mod(x, y)	整除函数 / 求模函数
allclose(x, y)	检查数组x和y元素是否几乎相等
power(x, y)	数组$x$的元素$x_i$和数组$y$的元素$y_i$，计算$x_i^{y_i}$
maximum(x, y) / fmax(x, y)	两两比较元素获取最大值 / 获取最大值（忽略NaN）
minimum(x, y) / fmin(x, y)	两两比较元素获取最小值 / 获取最小值（忽略NaN）
inner(x, y)	内积运算
cross(x, y) / outer(x, y)	叉积运算 / 外积运算
intersect1d(x, y)	计算x和y的交集，返回这些元素构成的有序数组
union1d(x, y)	计算x和y的并集，返回这些元素构成的有序数组
in1d(x, y)	返回由判断x 的元素是否在y中得到的布尔值构成的数组
setdiff1d(x, y)	计算x和y的差集，返回这些元素构成的数组
setxor1d(x, y)	计算x和y的对称差，返回这些元素构成的数组
'''

#处理数组函数
'''
unique	去除数组重复元素，返回唯一元素构成的有序数组
copy	返回拷贝数组得到的数组
sort	返回数组元素排序后的拷贝
split / hsplit / vsplit	将数组拆成若干个子数组
stack / hstack / vstack	将多个数组堆叠成新数组
concatenate	沿着指定的轴连接多个数组构成新数组
append / insert	向数组末尾追加元素 / 在数组指定位置插入元素
argwhere	找出数组中非0元素的位置
extract / select / where	按照指定的条件从数组中抽取或处理数组元素
flip	沿指定的轴翻转数组中的元素
fromiter	通过迭代器创建数组对象
fromregex	通过读取文件和正则表达式解析获取数据创建数组对象
repeat / tile	通过对元素的重复来创建新数组
roll	沿指定轴对数组元素进行移位
resize	重新调整数组的大小
place / put	将数组中满足条件的元素/指定的元素替换为指定的值
ptp	沿指定的轴计算极差（最大值与最小值的差）
median	沿指定轴计算中位数
partition	用选定的元素对数组进行一次划分并返回划分后的数组

上面的resize函数和ndarray对象的resize方法是有区别的，resize函数在调整数组大小时会重复数组中的元素作为填补多出来的元素的值，
而ndarry对象的resize方法是用0来填补多出来的元素。
'''

In [ ]:
'''
#矩阵运算
创建矩阵对象。
m1 = np.matrix('1 2 3; 4 5 6')
#矩阵属性
A	获取矩阵对象对应的ndarray对象
A1	获取矩阵对象对应的扁平化后的ndarray对象
I	可逆矩阵的逆矩阵
T	矩阵的转置
H	矩阵的共轭转置
shape	矩阵的形状
size	矩阵元素的个数
#NumPy的linalg模块
diag	以一维数组的形式返回方阵的对角线元素或将一维数组转换为方阵（非对角元素元素为0）
vdot	向量的点积
dot	数组的点积
inner	数组的内积
outer	数组的叉积
trace	计算对角线元素的和
norm	求模运算
det	计算行列式的值（在方阵上计算得到的标量）
matrix_rank	计算矩阵的秩
eig	计算矩阵的特征值（eigenvalue）和特征向量（eigenvector）
inv	计算非奇异矩阵（$n$阶方阵）的逆矩阵
pinv	计算矩阵的摩尔-彭若斯（Moore-Penrose）广义逆
qr	QR分解（把矩阵分解成一个正交矩阵与一个上三角矩阵的积）
svd	计算奇异值分解（singular value decomposition）
solve	解线性方程组，方阵
lstsq	计算最小二乘解
'''
